import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useGetPokemonByNameQuery } from "../service";

export default function Home({}) {
  const { data, error, isLoading } = useGetPokemonByNameQuery("bulbasaur");
  console.log("PROP: ", { data, error, isLoading });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hi</h1>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
